### ISSUE TITLE
Obesity being calculated with weight percentile instead of BMI percentile?

### ISSUE THREAD

**Issue by rustygeldmacher** [smart-on-fhir/growth-chart-app#11]
Hi there!

At Iora Health, we are currently rolling out a trial of this incredible component in order for our providers to have immediate access to growth charts during pediatric patient visits. So far, the reception has been overwhelming -- our staff and our patients love it! Thanks for the amazing work.

One of our providers recently pointed out a potential issue with the "parent view" -- she had a patient with weight in the 91st percentile and BMI in the 97th percentile. According to the CDC definition of childhood obesity (http://www.cdc.gov/obesity/childhood/defining.html), the patient should be labeled "obese" in the parent view, but instead was labeled "overweight".

We suspect that perhaps the obesity measure is being calculated using the weight percentile rather than the BMI percentile? If so, was that intentional, and is it possible to configure the component to use BMI instead?

Thanks again for the amazing work!

**Comment by nschwertner** [comment]
Thank you very much for the feedback. We will investigate

**Comment by rustygeldmacher** [comment]
Thanks @nschwertner -- any word on this? We're loving this app by the way!

**Comment by nschwertner** [comment]
Thank you, @rustygeldmacher Vlad added a fix (see above), but was not able to merge it into this repo (GitHUB has placed him on a perpetual permissions invite). I will run a pull request through my account to accelerate

**Comment by nschwertner** [comment]
Fixed via https://github.com/smart-on-fhir/growth-chart-app/pull/14

**Comment by rustygeldmacher** [comment]
Thanks @nschwertner that is awesome!
