### ISSUE TITLE
"Patient Not Found" error

### ISSUE THREAD

**Issue by allowishus** [smart-on-fhir/growth-chart-app#24]
Hopefully someone has seen this error - I'm receiving an error after selecting the sample patient. "There was an error loading the application: Patient not found." 

The documentation states that the patient data should come with the access token response from the authorization server. In this case, it doesn't happen. I looked for errors in the app requests but didn't find any. 

The problems appears on the growth-chart app. The "authorize" request includes the launch identifier and the app is correctly authorized. Despite this, when the access token is requested, the response doesn't contains the "patient" parameter. Because of that the growth-chart app cannot retrieve the patient data from the api-server, therefore throws an error. I can't figure out why the "patient" parameter is not defined.

[IssueSummary.pdf](https://github.com/smart-on-fhir/growth-chart-app/files/714471/IssueSummary.pdf)

**Comment by medapptech** [comment]
This sounds like a problem which is not specific to this app, but rather something in your infrastructure. Would you mind posting this to the SMART on FHIR Google Group (https://groups.google.com/forum/#!forum/smart-on-fhir) and we will see what we can do to help you debug

**Comment by nschwertner** [comment]
This sounds like a problem which is not specific to this app, but rather something in your infrastructure. Would you mind posting this to the SMART on FHIR Google Group (https://groups.google.com/forum/#!forum/smart-on-fhir) and we will see what we can do to help you debug

**Comment by Venkatramanaryams** [comment]
@jmandel can you tell me?
