### ISSUE TITLE
Error running app: npm run serve

### ISSUE THREAD

**Issue by AshwinRoh83** [smart-on-fhir/growth-chart-app#25]
verbose stack Error: growthchart@0.1.0 serve: `./node_modules/http-server/bin/http-server -p 8000 -c-1 .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid growthchart@0.1.0
16 verbose cwd C:\mystuff\gitprojects\smart-fhir
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
19 error node v6.9.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error growthchart@0.1.0 serve: `./node_modules/http-server/bin/http-server -p 8000 -c-1 .`
22 error Exit status 1
23 error Failed at the growthchart@0.1.0 serve script './node_modules/http-server/bin/http-server -p 8000 -c-1 .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the growthchart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./node_modules/http-server/bin/http-server -p 8000 -c-1 .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs growthchart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls growthchart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nschwertner** [comment]
Just tested the deployment steps from the readme: `npm install` and `npm run serve`
Worked fine on my machine (OSX 10.11.6). Please debug your local environment
