### ISSUE TITLE
issue with fetchAll & read

### ISSUE THREAD

**Issue by dpopcmh** [smart-on-fhir/growth-chart-app#5]
load-fhir-data.js, line 20-22 was recently changed to use .read() and .api.fetchAll(...),
however, the supporting methods do not appear to be checked in.
When updating to latest on Master, these lines failed with the below exception:

var ptFetch = smart.patient.read();
var vitalsFetch = smart.patient.api.fetchAll({type: "Observation", query: {code: {$or: ['3141-9', '8302-2', '8287-5', '39156-5', '18185-9', '37362-1', '11884-4']}}});
var familyHistoryFetch = smart.patient.api.fetchAll({type: "FamilyMemberHistory"});

Uncaught TypeError: Cannot read property 'read' of undefined (load-fhir-data.js:20)
  onReady	(load-fhir-data.js:20)
  (anonymous function)	(fhir-client.js:200)
  fire	 (fhir-client.js:10245)
  self.fireWith	(fhir-client.js:10357)
  deferred.(anonymous function)	(fhir-client.js:10447)
  (anonymous function)	(fhir-client.js:59)
  (anonymous function)	(fhir-client.js:4301)

**Comment by nschwertner** [comment]
Hmm. Sounds like a mismatch between the app and the local client that you are using. Are you using the client from `npm`? I think that we need to update the version hosted there (note to self)...

**Comment by nschwertner** [comment]
Resolved in https://github.com/smart-on-fhir/growth-chart-app/commit/6d63ab348d92057b58ed08f801591d5f1cb0ec20
