### ISSUE TITLE
No 'state' parameter found. Please (re)launch the app.

### ISSUE THREAD

**Issue by hexicalsystems** [smart-on-fhir/growth-chart-app#62]
Hello, I get the above message when started the app. I couldn't get into the app.     Please advise how to get started here. 

Message:  No 'state' parameter found. Please (re)launch the app.

System Info:  
npm 6.14.4
MacOS Catalina: 10.15.7
Chrome:  91.0
Firefox: 91.0

**Comment by vlad-ignatov** [comment]
As the message sates "Please (re)launch". Are you launching it as a SMART app? It cannot be opened directly. Try https://launch.smarthealthit.org.

**Comment by hexicalsystems** [comment]
Got it.  I launched it successfully with:  

http://127.0.0.1:9000/launch.html?launch=eyJhIjoiMSJ9&iss=https%3A%2F%2Flaunch.smarthealthit.org%2Fv%2Fr4%2Ffhir

Thank you for the quick response.

**Comment by Dtphelan1** [comment]
Seeing as this has been addressed, we're closing this issue.
